[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.5.5", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.10.2", default-features = false, features = ["wry"] }
tokio = { version = "1.49.0", features = [
  "io-util",
  "sync",
  "process",
  "rt-multi-thread",
  "macros",
  "time",
] }
git2 = "0.20.4"
tauri-plugin-dialog = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
uuid = { version = "1.8", features = [
  "v4", # keep if using Uuid::new_v4()
  "v5", # only if you call Uuid::new_v5()
  "serde", # keep — you're deserializing/serializing
] }

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[profile.dev]
opt-level = 0
debug = 0
incremental = true
codegen-units = 256
split-debuginfo = "unpacked"

# Compile all deps at opt-level 3, only your code stays unoptimized
[profile.dev.package."*"]
opt-level = 3

[profile.release]
panic = "abort" # Strips expensive panic clean-up logic
codegen-units = 1 # Allows LLVM to perform better optimization at the cost of compile time
lto = true # Enables Link-Time Optimizations
opt-level = "s" # Optimizes for binary size. Use "3" for max speed.
strip = true # Ensures debug symbols are removed
